// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using entrevista.Models;

namespace entrevista.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211108212316_firstMigration")]
    partial class firstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("entrevista.Models.Empresa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("direccion");

                    b.Property<string>("email");

                    b.Property<string>("razonSocial");

                    b.Property<int>("telefono");

                    b.Property<string>("web");

                    b.HasKey("id");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("entrevista.Models.Persona", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Empresaid");

                    b.HasKey("id");

                    b.HasIndex("Empresaid");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("entrevista.Models.Persona", b =>
                {
                    b.HasOne("entrevista.Models.Empresa")
                        .WithMany("contactos")
                        .HasForeignKey("Empresaid");
                });
#pragma warning restore 612, 618
        }
    }
}
